name: CI
on: push
jobs:
  rclone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: rclone
      uses: wei/rclone@v1
      env:
        RCLONE_CONF: ${{ secrets.rclone }}
      with:
        args: copy /github/workspace/notebooks drive:Colab\ Notebooks
